### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/washu#17]
```
[2017-10-03 18:38:47] H3K27ac Consensus report of the regions
[2017-10-03 18:38:47] Process: bash -c /home/oshpynov/work/washu/reports/chip_seq_report.py /scratch/artyomov_lab_aging/chipseq_analysis/hg19/hg19.chrom.sizes **.bed
[2017-10-03 18:44:11] writing FRiP table
[2017-10-03 18:44:11] writing peaks length
[2017-10-03 18:44:11] Traceback (most recent call last):
[2017-10-03 18:44:11]   File "/home/oshpynov/work/washu/reports/chip_seq_report.py", line 159, in <module>
[2017-10-03 18:44:11]     main()
[2017-10-03 18:44:11]   File "/home/oshpynov/work/washu/reports/chip_seq_report.py", line 155, in main
[2017-10-03 18:44:11]     process(args[1], args[2:])
[2017-10-03 18:44:11]   File "/home/oshpynov/work/washu/reports/chip_seq_report.py", line 44, in process
[2017-10-03 18:44:11]     write_peak_length(peaks)
[2017-10-03 18:44:11]   File "/home/oshpynov/work/washu/reports/chip_seq_report.py", line 108, in write_peak_length
[2017-10-03 18:44:11]     for line in read_all_lines(peak_file):
[2017-10-03 18:44:11]   File "/home/oshpynov/work/washu/reports/chip_seq_report.py", line 146, in read_all_lines
[2017-10-03 18:44:11]     return f.readlines()
[2017-10-03 18:44:11] MemoryError
[2017-10-03 18:44:11] recalculating /scratch/artyomov_lab_aging/chipseq_analysis/configs/Y20O20/peaks/H3K27ac: [FAILED] after 4.391 h
Caused by: org.jetbrains.bio.util.ExecException: Process stopped with exit code 1
        at org.jetbrains.bio.util.Exec.exec$crux(Exec.kt:55)
        at org.jetbrains.bio.util.ExecKt.exec(Exec.kt:16)
        at org.jetbrains.bio.util.ExecKt.exec$default(Exec.kt:15)
        at org.jetbrains.bio.tools.Washu.makeReport(Washu.kt:124)
        at org.jetbrains.bio.experiments.histones.ZinbraWeakConsensusExperiment$doCalculations$$inlined$forEach$lambda$1.invoke(ChipseqAnalysisPipeline.kt:112)
        at org.jetbrains.bio.experiments.histones.ZinbraWeakConsensusExperiment$doCalculations$$inlined$forEach$lambda$1.invoke(ChipseqAnalysisPipeline.kt:94)
        at org.jetbrains.bio.tools.WashuKt$runBatch$1.invoke(Washu.kt:272)
        at org.jetbrains.bio.tools.WashuKt$runBatch$1.invoke(Washu.kt)
        at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$$special$$inlined$time$lambda$1.invoke(PathExtensions.kt:261)
        at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$$special$$inlined$time$lambda$1.invoke(PathExtensions.kt)
        at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1.invoke(PathExtensions.kt:369)
        at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1.invoke(PathExtensions.kt)
        at org.jetbrains.bio.util.LockManager.synchronized(LockManager.kt:38)
        at org.jetbrains.bio.util.PathExtensionsKt.checkOrRecalculate(PathExtensions.kt:246)
        at org.jetbrains.bio.util.PathExtensionsKt.checkOrRecalculate$default(PathExtensions.kt:243)
        at org.jetbrains.bio.tools.WashuKt.runBatch(Washu.kt:269)
        at org.jetbrains.bio.tools.WashuKt.runBatch$default(Washu.kt:268)
        at org.jetbrains.bio.experiments.histones.ZinbraWeakConsensusExperiment.doCalculations(ChipseqAnalysisPipeline.kt:106)
        at org.jetbrains.bio.experiments.Experiment.run(Experiment.kt:49)
        at org.jetbrains.bio.experiments.histones.ChipseqAnalysisPipeline$Companion.main(ChipseqAnalysisPipeline.kt:69)
        at org.jetbrains.bio.experiments.histones.ChipseqAnalysisPipeline.main(ChipseqAnalysisPipeline.kt)
```

**Comment by PetrTsurinov** [comment]
Obsolete, cannot reproduce.
